# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cserver.proto\"O\n\x10SumAmountRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x15\n\rdatetime_from\x18\x02 \x01(\x03\x12\x13\n\x0b\x64\x61tetime_to\x18\x03 \x01(\x03\"E\n\x11SumAmountResponse\x12\x1d\n\x15time_for_execution_ms\x18\x01 \x01(\x02\x12\x11\n\ttotal_sum\x18\x02 \x01(\x02\x32?\n\x06Server\x12\x35\n\nsum_amount\x12\x11.SumAmountRequest\x1a\x12.SumAmountResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'server_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SUMAMOUNTREQUEST']._serialized_start=16
  _globals['_SUMAMOUNTREQUEST']._serialized_end=95
  _globals['_SUMAMOUNTRESPONSE']._serialized_start=97
  _globals['_SUMAMOUNTRESPONSE']._serialized_end=166
  _globals['_SERVER']._serialized_start=168
  _globals['_SERVER']._serialized_end=231
# @@protoc_insertion_point(module_scope)
